[server]
headless = true
enableStaticServing = true
maxUploadSize = 500

[theme]
base = "dark"
primaryColor = "#6C5DD3"
backgroundColor = "#0F111E"
secondaryBackgroundColor = "#161A2B"
textColor = "#F4F5FF"
font = "sans serif"
