[server]
headless = true
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#4C5BD5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F6F8FE"
textColor = "#1F1F1F"
font = "sans serif"
